name: build scala containers and publish them to docker cloud

on: 
  workflow_call:
    inputs:
      java_version:
        required: true
        type: string

  
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: ${{ inputs.java_version }}
          cache: 'sbt'
     

