
name: build scala containers and publish them to docker cloud

on: 
  workflow_call:
    inputs:
      java_version:
        required: true
        type: string
      scala_version:
        required: true
        type: string
    secrets:
      docker_username:
        required: true
      docker_password:
        required: true
        
  
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: ${{ inputs.java_version }}
          cache: 'sbt'
          
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}    
          
      - name: build and test the image
        run: sbt ++${{ inputs.scala_version }} clean coverage test coverageOff docker:publishLocal
        
        
        
